# Generated by Django 3.1.7 on 2021-04-09 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectorJob',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='area_of_interest_detail',
            new_name='areaofinterest_detail',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='phoneno',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AddField(
            model_name='education',
            name='starting_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Phd', 'Male'), ('Mtech/MA/MSc/MCom/MBA', 'Masters'), ('BE/Btech/BA/BSc/BCom', 'Bachelors'), ('12th', 'Intermediate'), ('10th', 'High School')], max_length=50),
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_detail', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeBuilder.person')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracurricular_detail', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeBuilder.person')),
            ],
        ),
    ]
