# Generated by Django 3.1.7 on 2021-04-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('objective', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('university', models.URLField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('starting_year', models.DateField(blank=True)),
                ('passing_year', models.DateField(blank=True)),
                ('univResult', models.CharField(blank=True, max_length=5)),
                ('intermediateSchool', models.CharField(blank=True, max_length=100)),
                ('intermediateSubjects', models.CharField(blank=True, max_length=100)),
                ('intermediateMarks', models.CharField(blank=True, max_length=15)),
                ('highSchool', models.CharField(blank=True, max_length=100)),
                ('highSchoolSubjects', models.CharField(blank=True, max_length=100)),
                ('highSchoolMarks', models.CharField(blank=True, max_length=15)),
                ('jobTitle', models.CharField(max_length=100)),
                ('projectTitle', models.CharField(max_length=100)),
                ('jobStartDate', models.DateField(blank=True)),
                ('jobEndDate', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('skill_detail', models.TextField(max_length=200)),
                ('language_detail', models.TextField(max_length=200)),
                ('areaofinterest', models.TextField(blank=True, max_length=100)),
                ('extracurricular_detail', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='areaofinterest',
            name='person',
        ),
        migrations.RemoveField(
            model_name='education',
            name='person',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='person',
        ),
        migrations.RemoveField(
            model_name='extracurricular',
            name='person',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='person',
        ),
        migrations.RemoveField(
            model_name='professionalskills',
            name='person',
        ),
        migrations.DeleteModel(
            name='Academics',
        ),
        migrations.DeleteModel(
            name='AreaOfInterest',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='ExtraCurricular',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ProfessionalSkills',
        ),
    ]
