# Generated by Django 3.1.7 on 2021-04-11 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0004_auto_20210411_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='areaofinterest',
            new_name='areaOfInterest',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='extracurricular_detail',
            new_name='extracurricularDetail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passing_year',
            new_name='highSchoolPassingYear',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='starting_year',
            new_name='highSchoolStartingYear',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='language_detail',
            new_name='languageDetail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skill_detail',
            new_name='skillDetail',
        ),
        migrations.AddField(
            model_name='profile',
            name='currentYear',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediatePassingYear',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediateStartingYear',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projectDescription',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='projectEndDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projectStartDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='univPassingYear',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='univStartingYear',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
