# Generated by Django 3.1.7 on 2021-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0005_auto_20210411_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='jobDescription',
        ),
    ]
