# Generated by Django 3.1.7 on 2021-04-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0009_auto_20210411_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currentYear',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univResult',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
